### PR TITLE
add test file for mutual TLS

### PR DESCRIPTION
**Pull request by lihongan**
@bmeng @zhaozhanqi Please help review. thanks

### CODE REVIEW

**Comment by bmeng** [comment]
Can the file name be more specific? The test2.crt and test2.key are too meaningless.

**Comment by lihongan** [comment]
rename to www.test2.com.crt/key since the certificate CN is www.test2.com.

**Comment by zhaozhanqi** [comment]
hmm, does the ca.key need for our testing?

**Comment by lihongan** [comment]
The ca.key is not needed for testing but for making intermediate CA, new server/client certificates, and CRL.

**Comment by zhaozhanqi** [comment]
yeah, this file should be kept in secret.  any others willl be able to sign the certificates for your CA. just curious if there any risk here.

**Comment by bmeng** [comment]
All the keys and certs are used for testing only. I cannot see any security risk here unless you want the test certs for other usages.

Put the ca.key here, in case when we want to generate new crt but we cannot remember which ca.key we were used.

**Pull request merged**
