### PR TITLE
Update Deployment API version

### PR DESCRIPTION
**Pull request by duanwei33**
Update Deployment API version to apps/v1.

### CODE REVIEW

**Comment by liangxia** [comment]
Will the change affect the testing on old OCP versions ?

**Comment by duanwei33** [comment]
@liangxia Thanks for the consideration.
I checked the Deployment API version(I guess compatibility support should have) as below: 
1.6-: extensions/v1beta1
1.6-1.9: apps/v1beta1
1.9+: apps/v1
And OCP4.1 is based on v1.13?

I guess there is low risk, of cause the safer way is changing path in .feature, it is handled by release.  
What is your option?

**Comment by liangxia** [comment]
We also need to check the test cases which use this test file, whether it is also a 3.x test case, as test files are shared across 3.x and 4.x

**Comment by duanwei33** [comment]
I checked the v3 branch, there is only one case OCP-10168 uses this file, it run on both 3.x and 4.x, OCP 3.11 is based on k8s 1.11, so I think it is acceptable.

**Pull request merged**
