### PR TITLE
Add for OCP-12777/OCP-10873

### PR DESCRIPTION
**Pull request by xingxingxia**
@wsun1 help merge it for https://github.com/openshift/cucushift/pull/6502
@akostadinov could you give me the merge permission for this repo?
Thank you all!

### CODE REVIEW

**Comment by akostadinov** [comment]
I think the original idea was to have one/two team members who have merge rights to review what's going in here. But it is up to the team to decide who to get merge rights and how reviews should be conducted.

I'll merge this one as it makes sense to me. From team structure it looks like @yapei must tell whether to grant you merge rights and how reviews should work. Please talk to her.

**Comment by xingxingxia** [comment]
@akostadinov this week I transferred from UI to Master. Master has nobody with the merge right. Haoran Wang from Master transferred to SRE.

**Comment by yapei** [comment]
yeah as @xingxingxia said, he moved to Master and is the team lead now, so it should make sense to grant merge permission.

**Comment by akostadinov** [comment]
Thank you, didn't know this.

**Pull request merged**
