### PR TITLE
Add testfiles for testing sticky session upgrade

### PR DESCRIPTION
**Pull request by duyanyan**
@bmeng

### CODE REVIEW

**Comment by bmeng** [comment]
1. What is the difference between the existing test files and the new ones?
2. Do we need to put all the upgrade related test files in to an unified place?

**Comment by duyanyan** [comment]
1. Due to the pod without rc will be deleted after upgrade, the current caddy-docker file can not use for upgrade sticky session testing
2. I am not sure whether other teams have same requirement, if yes, we could use a unified place to save these files.

**Comment by bmeng** [comment]
Please confirm  with anli or liujia about the 2nd point

**Comment by anpingli** [comment]
@bmeng, there is no unified place to store upgrade testing file.  In case to lose your application during upgrade, you have to add RC for your application

**Comment by bmeng** [comment]
Thanks, merged.

**Pull request merged**
