### PR TITLE
Add file policy.json and policy_empty.json

### PR DESCRIPTION
**Pull request by kasturinarra**
Adding file policy.json and policy_empty.json to test OCP-12518

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 @xingxingxia can you please help review this ?

**Comment by zhouying7780** [comment]
LGTM , thanks. @xingxingxia could you please help merge , thanks.

**Comment by xingxingxia** [comment]
@kasturinarra for policy.json, better to rename it in case others confused if intended or mistaken, e.g. policy_no_content.json, thanks

**Comment by kasturinarra** [comment]
@xingxingxia updated the PR, could you please help check ? Thanks

**Pull request merged**
