### PR TITLE
Add pod file for test OCP-24240

### PR DESCRIPTION
**Pull request by kasturinarra**
Add pod.yaml fie for test OCP-24240

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 can you please help review ? Thanks

**Comment by kasturinarra** [comment]
@xingxingxia could you please help merge ? Thanks !!

**Comment by xingxingxia** [comment]
@zhouying7780 minor advice: once you add lgtm, suggest you @ me meantime to save one operation of @kasturinarra , thanks.

**Comment by xingxingxia** [comment]
@kasturinarra there are common use pods like https://raw.githubusercontent.com/openshift/origin/master/examples/hello-openshift/hello-pod.json and v3-testfiles pods/hello-pod.json. Not sure if they're already fine?
Merging, though.

**Pull request merged**
