### PR TITLE
Remove zone us-east-1d in the sc

### PR DESCRIPTION
**Pull request by chao007**

### CODE REVIEW

**Comment by liangxia** [comment]
You may need a new test file as the current one is used in 3.x

**Comment by chao007** [comment]
We can still use it in 4.x, yes?

**Comment by liangxia** [comment]
The 3.x which test zones will not work then.

**Comment by chao007** [comment]
It does not impact 3.x.
We only use this sc to dynamic provison io1 type ebs volume.

**Comment by liangxia** [comment]
Then LGTM

**Pull request merged**
