### PR TITLE
add logging external server playbooks

### PR DESCRIPTION
**Pull request by anpingli**
@pruan-rht  @wsun1  Could we use playbooks as directory names?

### CODE REVIEW

**Comment by anpingli** [comment]
@pruan-rht @wsun1  
1) externalserver.yml playbooks are used to setup rsyslog/fluend on the separated host which is is not suitable for automation.
2) To deploy internal-forward-fluentd & internal-rsyslog.yml
 ansible-playbook -i hosts  logging_metrics/playbooks/internal-forward-fluentd.yml
3) To unddeploy internal-forward-fluentd & internal-rsyslog.yml 
 ansible-playbook -i hosts  logging_metrics/playbooks/internal-forward-fluentd.yml -e test_clear=true

**Comment by anpingli** [comment]
@juzhao, Test

**Comment by juzhao** [comment]
@anpingli 
Could be viewed?

**Comment by pruan-rht** [comment]
LGTM, I can merge it if there is not objection from the rest of the team.

**Comment by wsun1** [comment]
@juzhao Test

**Comment by juzhao** [comment]
@juzhao
This is a testing

**Pull request merged**
