### PR TITLE
Adding testing rc files

### PR DESCRIPTION
**Pull request by yapei**
Add a testing file which is used to create a RC that matches a service

### CODE REVIEW

**Comment by bmeng** [comment]
Is it intended to test start openshift origin in a docker container or just test the rc with service?

**Comment by yapei** [comment]
Just to create a rc which matches with a service

**Comment by bmeng** [comment]
is it possible to use a simple image/rc here? it will cost more resources to run a openshift origin in container

**Comment by yapei** [comment]
Image is changed, please help check

**Pull request merged**
