### PR TITLE
Set limits for OCP-11195

### PR DESCRIPTION
**Pull request by maybelinot**
merge only if you intentionally came here to do that

### CODE REVIEW

**Comment by maybelinot** [comment]
@xiaocwan @xingxingxia Can you check this change please?

**Comment by xingxingxia** [comment]
LGTM
But oh, FYI, there're two
https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json
VS
https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/double_containers.json
Images yapei/... and jhou/... are same AFAIK
@xxing has updated the former. Updating two or removing one from repo, both LGTM for me, though

**Comment by maybelinot** [comment]
@xingxingxia updated, can we somehow make sure that this file wasn't used anywhere else except cucushift?
ref https://github.com/openshift/cucushift/pull/4880

**Comment by xingxingxia** [comment]
Great, LGTM. Other place that possibly refers to the https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/double_containers.json is solely TC, I think, which doesn't matter much.

**Pull request merged**
